print("hello world".capitalize())
print("Hello World".casefold())
print("hello".center(10, "-"))
print("banana".count("a"))
print("hello".encode())
print("hello world".endswith("world"))
print("hello\tworld".expandtabs(4))
print("hello world".find("world"))
print("Hello, {}!".format("Alice"))
data = {"name": "Alice"}
print("Hello, {name}!".format_map(data))
print("hello world".index("world"))
print("hello123".isalnum())
print("hello".isalpha())
print("hello".isascii())
print("123".isdecimal())
print("123".isdigit())
print("hello_world".isidentifier())
print("hello".islower())
print("123".isnumeric())
print("hello".isprintable())
print("   ".isspace())
print("Hello World".istitle())
print("HELLO".isupper())
print(",".join(["a", "b", "c"]))
print("hello".ljust(10, "-"))
print("HELLO".lower())
print("   hello".lstrip())
trans = str.maketrans("a", "o")
print("apple".translate(trans))
print("hello world".partition(" "))
print("hello world".replace("world", "Python"))
print("hello hello".rfind("hello"))
print("hello hello".rindex("hello"))
print("hello".rjust(10, "-"))
print("hello world".rpartition(" "))
print("a,b,c".rsplit(","))
print("hello   ".rstrip())
print("a,b,c".split(","))
print("hello\nworld".splitlines())
print("hello world".startswith("hello"))
print("   hello   ".strip())
print("Hello World".swapcase())
print("hello world".title())
trans = str.maketrans("aeiou", "12345")
print("hello".translate(trans))
print("hello".upper())
print("42".zfill(5))
